name: Critical Path
favicon: null
layout_spectrum: 0.35355392773635685
typography_spectrum: 0.5549003332853317
title: Critical path
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0.8920354628935456
  saturation: 0.4690783906262368
  rhythmicContrast: 0.5853451744187623
purpose: []
